name: Samsung Ext4 Firmware Extractor.

on:
  workflow_dispatch:
    inputs:
      Firmware_Download_URL:
        description: 'URL to download the Samsung firmware'
        required: true

jobs:
  build:
    runs-on: debian-11

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Downloading firmware.
        run: |
          cd && sudo apt-get update && sudo apt install -y p7zip-full lz4 android-sdk-libsparse-utils wget python3 git zlib1g-dev libbz2-dev libssl-dev
